$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
    ignore_empty_input = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = eDP-1
    path = ~/Pictures/Background.png
    blur_passes = 3
}

input-field {
    monitor = eDP-1
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(fabd2fff) rgba(83a598ff) 45deg
    check_color = rgba(b8bb26ff) rgba(fabd2fff) 120deg
    fail_color = rgba(fb4934ff) rgba(d3869bff) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor = eDP-1
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, -50
    halign = center
    valign = top
}

# DATE
label {
    monitor = eDP-1
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, -200
    halign = center
    valign = top
}