#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = nm-applet & blueman-applet
exec-once = waybar & swaync
exec-once = hypridle & swaybg -i ~/Pictures/Background.png
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
