###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileBrowser = thunar
$menu = fuzzel
$browser = google-chrome-stable
$scripts = $HOME/.config/scripts
